### ISSUE TITLE
NextCloudの証明書が切れてる

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#93]

**Comment by jacopen** [comment]
gnginx-certbotイメージで自動化している・・・はずだけど、ちゃんと動いてない

```
  frontend:
    restart: always
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - CERTBOT_EMAIL=jacopen@gmail.com
      - ENVSUBST_VARS=FQDN
      - FQDN=nextcloud.cloudnativedays.jp
    volumes:
      - /data/nginx/conf.d:/etc/nginx/user.conf.d:ro
      - /data/letsencrypt:/etc/letsencrypt
```
